[WIP] EC-CUBE 4.0ブランチに移植
EC-CUBE/coupon-plugin pull request #77
Opened 2018-08-10 09:47 UTC by nanasess

## #76からの変更点
- PurchaseFlow を使用するよう修正
- Order::setOrderCompleteMailMessage() を使用してメールの差し込みをするよう修正
- クーポン値引明細の集計方法を変更

## 値引の計算方法について

## 現状の課題

- ポイントとの併用ができない。 Processor の優先順位がポイントの方が高く、値引率で集計できなくなるため。 purchaseflow.yaml を手動で設定することで回避可能。
- 軽減税率に対応していない。値引率で集計する際、明細ごとに割引価格を集計するが、クーポン値引明細は1行なので、複数の税率に対応できない。クーポン明細を複数行で出力にすることで回避可能

## TODO

- クーポンの妥当性検証を CouponProcessor に移植する
- Event::onOrderEditComplete() を CouponStateProcessor に移植する
- ユニットテスト

2019-06-03 06:10 UTC, kiy0taka requested changes
ライセンス表記の修正もお願いします。

2019-06-03 06:10 UTC, kiy0taka commented on Service/PurchaseFlow/Processor/CouponProcessor.php
> +            $this->clearCoupon($itemHolder);
145行目で例外がスローされるのでこの行は実行されません。

2019-06-03 06:10 UTC, kiy0taka commented on Service/PurchaseFlow/Processor/CouponProcessor.php
> +            $this->clearCoupon($itemHolder);
138行目で例外がスローされるのでこの行は実行されません。

2019-06-03 06:10 UTC, kiy0taka commented on Service/PurchaseFlow/Processor/CouponProcessor.php
> +            $this->clearCoupon($itemHolder);
152行目で例外がスローされるのでこの行は実行されません。

2019-06-03 06:10 UTC, kiy0taka commented on Service/PurchaseFlow/Processor/CouponProcessor.php
> +            $this->clearCoupon($itemHolder);
159行目で例外がスローされるのでこの行は実行されません。

2019-06-03 06:10 UTC, kiy0taka commented on Service/PurchaseFlow/Processor/CouponProcessor.php
> +            $this->clearCoupon($itemHolder);
167行目で例外がスローされるのでこの行は実行されません。

2019-06-03 06:10 UTC, kiy0taka commented on Controller/CouponShoppingController.php
> +    private $shoppingService;
`ShoppingService` は存在しません。

2019-06-03 06:10 UTC, kiy0taka commented on Controller/CouponShoppingController.php
> +                    $Customer = $this->shoppingService->getNonMember($this->sessionKey);
`ShoppingService` は存在しません。

2019-06-03 06:10 UTC, kiy0taka commented on Controller/CouponShoppingController.php
> +                $Coupon = $this->couponRepository->findActiveCoupon($formCouponCd);
この辺の妥当性検証は`CouponProcessor`で実装されているので`PurchaseFlow`を利用してください。

2019-06-03 06:10 UTC, kiy0taka commented on Service/PurchaseFlow/Processor/CouponProcessor.php
> +        $lowerLimit = $Coupon->getCouponLowerLimit();
このコードは156行目の上にある方が可読性が高くなります。

2019-06-03 07:20 UTC, nanasess commented on Controller/CouponShoppingController.php
> +                $Coupon = $this->couponRepository->findActiveCoupon($formCouponCd);
ここのエラーハンドリングは、クーポン入力フォームにエラーメッセージを表示したいので、ここで実装しています。
(`CouponProcessor` で実装すると、注文確認画面にエラーメッセージを表示してしまうため)

2019-06-03 07:37 UTC, nanasess commented on Service/PurchaseFlow/Processor/CouponProcessor.php
> +        $lowerLimit = $Coupon->getCouponLowerLimit();
修正しました
https://github.com/EC-CUBE/coupon-plugin/pull/77/commits/93d781da7ccd45fc1a55b3051a6963e17621d98a

2019-06-03 07:38 UTC, nanasess commented on Service/PurchaseFlow/Processor/CouponProcessor.php
> +            $this->clearCoupon($itemHolder);
修正しました
https://github.com/EC-CUBE/coupon-plugin/pull/77/commits/c03f90a4077f90259d8b40dde3bac06747c3b0af

2019-06-03 07:38 UTC, nanasess commented on Service/PurchaseFlow/Processor/CouponProcessor.php
> +            $this->clearCoupon($itemHolder);
修正しました
https://github.com/EC-CUBE/coupon-plugin/pull/77/commits/c03f90a4077f90259d8b40dde3bac06747c3b0af

2019-06-03 07:41 UTC, nanasess commented on Service/PurchaseFlow/Processor/CouponProcessor.php
> +            $this->clearCoupon($itemHolder);
修正しました
https://github.com/EC-CUBE/coupon-plugin/pull/77/commits/13d1b2a1b4479f899cfd417c2adfc5acbbb9faa3

2019-06-03 07:41 UTC, nanasess commented on Service/PurchaseFlow/Processor/CouponProcessor.php
> +            $this->clearCoupon($itemHolder);
修正しました
https://github.com/EC-CUBE/coupon-plugin/commit/c03f90a4077f90259d8b40dde3bac06747c3b0af

2019-06-03 07:41 UTC, nanasess commented on Service/PurchaseFlow/Processor/CouponProcessor.php
> +            $this->clearCoupon($itemHolder);
修正しました
https://github.com/EC-CUBE/coupon-plugin/commit/c03f90a4077f90259d8b40dde3bac06747c3b0af

2019-06-03 07:49 UTC, nanasess commented
ライセンス表記修正しました

2019-06-05 04:47 UTC, kiy0taka commented on Controller/CouponShoppingController.php
> +                $Coupon = $this->couponRepository->findActiveCoupon($formCouponCd);
了解しました。ここはこれで行きましょう。

2019-06-05 04:52 UTC, kiy0taka approved these changes

2019-06-20 12:55 UTC, merged